name: Deploy Next.js site to Pages

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            bun.lockb
            node_modules
            .next/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}-

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun lint:ci

      - name: Run format
        run: bun format:ci

  build:
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            bun.lockb
            node_modules
            .next/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}-

      - name: Install dependencies with Bun
        run: bun install

      - name: Build with Next.js
        run: bun run next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Determine Deployment URL
        id: determine-url
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "url_prefix=''" >> $GITHUB_ENV
          else
            BRANCH_NAME=${{ github.ref_name }}
            echo "url_prefix='${BRANCH_NAME}'" >> $GITHUB_ENV
          fi

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: ./out
          branch: ${{ github.ref_name }}
          subdir: ${{ env.url_prefix }}
      
      - name: Print Deployment URL
        run: echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"


    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
